### ISSUE TITLE
Where to get: `ACTIONS_ID_TOKEN_REQUEST_TOKEN` && `ACTIONS_ID_TOKEN_REQUEST_URL`

### ISSUE THREAD

**Issue by rms1000watt** [glassechidna/ghaoidc#1]
Hi Aidan, thank you so much for putting this all together!!

The one piece I'm unclear of, is where do we these 2 values from?

- `ACTIONS_ID_TOKEN_REQUEST_TOKEN`
- `ACTIONS_ID_TOKEN_REQUEST_URL`

Thank you again!!

**Comment by tblankfielmann** [comment]
These are global environment variables in the GitHub Action Workflows. They only seem to be present once the workflow permissions have been set accordingly:

<img width="203" alt="Screenshot 2021-10-08 at 10 48 02" src="https://user-images.githubusercontent.com/59447837/136527069-080cfaf7-87d3-4c7c-bc18-99ceea5755f6.png">

**Comment by rms1000watt** [comment]
Thank you, I'll give this a shot

**Comment by donjmilligan** [comment]
This worked for me.

**Comment by rushikeshsp25** [comment]
It worked for me as well!

**Comment by andrewelliottatsolace** [comment]
fixed my issue
