### ISSUE TITLE
Issue after the IDP issuer url changed

### ISSUE THREAD

**Issue by alexpopaconst** [glassechidna/ghaoidc#3]
Hello! First of all, thank you for your awesome guide [here](https://awsteele.com/blog/2021/09/15/aws-federation-comes-to-github-actions.html).

I followed it and got it to work successfully. However, today I got an error regarding the OIDC issuer, and took a look again at your repo and guide and saw that it had changed from `vstoken.actions.githubusercontent.com` to `token.actions.githubusercontent.com`.
I made the change as well, but now I am getting another error: `InvalidIdentityToken: Incorrect token audience`.

Did by any chance something else change regarding the audience in the token? I could not see any other change in your guide or your repo that would suggest that. Thank you!

**Comment by alexpopaconst** [comment]
@manjotatwork Haven't fixed that yet. Was hoping that @aidansteele has some clue about it

**Comment by moali87** [comment]
I'm also running into this issue.  It would be nice if we could see the jwt token somehow.

**Comment by moali87** [comment]
The audience is now the org or your user.

aud: https://github.com/<User or Org>

@aidansteele

**Comment by moali87** [comment]
> @moali87: Thanks it's working now with aud as User/Org ... But I am wondering how you figured this out?

Lucky guess really.
